---
title: "hw03-doug-koerber"
author: "Doug Koerber"
output: github_document
---

### Basic Rankings
#### Salary
```{r}
library(ggplot2)
ggplot(data = teams, aes(x = reorder(team, salary), y = salary)) +
  geom_bar(stat = "identity", fill = "gray60") +
  geom_hline(aes(yintercept = mean(salary)), col = rgb(50, 172, 150, maxColorValue = 255), size = 2, alpha = 0.7) +
  coord_flip() +
  labs(x = "Team", y = "Salary (in millions)", title = "NBA Teams Ranked by Total Salary")
```

#### Total Points
```{r}
ggplot(data = teams, aes(x = reorder(team, points), y = points)) +
  geom_bar(stat = "identity", fill = "gray60") +
  geom_hline(aes(yintercept = mean(points)), col = rgb(50, 172, 150, maxColorValue = 255), size = 2, alpha = 0.7) +
  coord_flip() +
  labs(x = "Team", y = "Total Points", title = "NBA Teams Ranked by Total Points")
```

#### Efficiency
```{r}
ggplot(data = teams, aes(x = reorder(team, efficiency), y = efficiency)) +
  geom_bar(stat = "identity", fill = "gray60") +
  geom_hline(aes(yintercept = mean(efficiency)), col = rgb(50, 172, 150, maxColorValue = 255), size = 2, alpha = 0.7) +
  coord_flip() +
  labs(x = "Team", y = "Total Efficiency", title = "NBA Teams Ranked by Total Points")
```

```{r}
pc1 <- data.frame(teams$points3, teams$points2, teams$free_throws, teams$off_rebounds, teams$def_rebounds, teams$assists, teams$steals, teams$blocks, teams$turnovers, teams$fouls)
pca <- prcomp(pc1, scale. = TRUE)
names(pca)
eigs <- data.frame(eigenvalue = pca$sdev^2, prop = pca$sdev^2 / sum(pca$sdev^2))
eigs <- round(mutate(eigs, cumprop = cumsum(prop)), 4)
```

```{r}
pca_plot <- data.frame(teams$team, pca$x)
ggplot(data = pca_plot, aes(x = PC1, y = PC2)) +
  geom_text(aes(label = teams$team)) +
  geom_vline(xintercept = 0, col = "gray50") +
  geom_hline(yintercept = 0, col = "gray50") +
  labs(title = "PCA Plot: PC1 and PC2")
```

### Scaled PC1 Scores
```{r}
pca_plot <- mutate(pca_plot, PC1_scaled = 100 * ((PC1 - min(PC1)) / (max(PC1) - min(PC1))))
ggplot(data = pca_plot, aes(x = reorder(teams.team, PC1_scaled), y = PC1_scaled)) +
  geom_bar(stat = "identity", fill = "gray60") +
  coord_flip() +
  labs(x = "Team", y = "PC1 (Scaled to 100)", title = "NBA Teams Ranked by Scaled PC1")
```

